name: ExtraHardMode
main: me.ryanhamshire.ExtraHardMode.ExtraHardMode
softdepend: [Multiverse-Core, My Worlds, MystCraft, Transporter]
dev-url: http://dev.bukkit.org/server-mods/fun-hard-mode
version: 2.2
commands:
permissions:
    extrahardmode.bypass:
        description: Grants bypass permission for some extra hard mode rules.
        default: op